### ISSUE TITLE
Could not determine the dependencies of task ':flutter_braintree:compileDebugAidl'.

### ISSUE THREAD

**Issue by marcoheine** [pikaju/flutter-braintree#49]
Hi,

when I want to build the Android App, I get this error:

> FAILURE: Build failed with an exception.

> * What went wrong:
> Could not determine the dependencies of task ':flutter_braintree:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_braintree:debugCompileClasspath'.
   > Could not find org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :flutter_braintree > com.braintreepayments.api:three-d-secure:3.14.2`

Version 1.1.0+1

**Comment by daoibrahim** [comment]
Same issue here. Any solution?

**Comment by nicolobozzato** [comment]
I think the new hotfix miss implementation of these lines in the build gradle
        maven {
            url "https://cardinalcommerce.bintray.com/android"
            credentials {
                username 'braintree-team-sdk@cardinalcommerce'
                password '220cc9476025679c4e5c843666c27d97cfb0f951'
            }
        }
Like indicated here:
https://developers.braintreepayments.com/guides/3d-secure/migration/android/v3

Hope @pikaju can fix that.
In the meanwhile to avoid the problem I kept the fork made by another user here 
https://github.com/pikaju/flutter-braintree/issues/43

**Comment by RalphNoel** [comment]
Same issue, can you give the solution for this ? @marcoheine

**Comment by abbas-25** [comment]
same issue, tried multiple solutions. Can't gather what I am missing? Anyone with a solution, please?

**Comment by mensur-durakovic** [comment]
@marcoheine same problem here, so I downgraded to version 1.1.0 and it works fine.

@pikaju is version 1.1.0 safe to use? I saw some security changes mentioned in description...

**Comment by pikaju** [comment]
Sorry for the wait, this is (hopefully) fixed in version `1.2.1`.

**Comment by jmarrr** [comment]
@pikaju This issue still persist I have `flutter_braintree: ^1.2.1` on my pubspec

**Comment by mensur-durakovic** [comment]
@jmarrr same here, it is still throwing the same error. 

@pikaju I suggest you make fresh new clean project, try to follow the steps in the readme and it is reproducable 100%, try it on any Android device or emulator, it is the same.

**Comment by andesappal** [comment]
Issue is back on scene https://github.com/pikaju/flutter-braintree/issues/74

**Comment by andesappal** [comment]
> I think the new hotfix didn't implement these lines of code in the _android/build.gradle_
> 
> ```
>         maven {
>             url "https://cardinalcommerce.bintray.com/android"
>             credentials {
>                 username 'braintree-team-sdk@cardinalcommerce'
>                 password '220cc9476025679c4e5c843666c27d97cfb0f951'
>             }
>         }
> ```
> 
> Like indicated here:
> https://developers.braintreepayments.com/guides/3d-secure/migration/android/v3
> 
> Hope @pikaju can fix that.
> In the meanwhile to avoid the problem I'm using the fork made by another user here in this thread
> #43

Storing credentials in the app is not good practice at all.

**Comment by andesappal** [comment]
This worked https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side#generate-a-client-token
