### ISSUE TITLE
 Could not determine the dependencies of task ':flutter_braintree:compileDebugAidl'.

### ISSUE THREAD

**Issue by bipindubey-technoark** [pikaju/flutter-braintree#59]
When i am running a flutter project it is giving following error

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_braintree:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_braintree:debugCompileClasspath'.
   > Could not find org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :flutter_braintree > com.braintreepayments.api:three-d-secure:3.14.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1

Pubspec.yaml:

    flutter_braintree: ^1.1.0+1

THANKS

**Comment by pikaju** [comment]
This is hopefully fixed in version `1.2.1`. Let me know if it works!

**Comment by andesappal** [comment]
Issue is back on scene https://github.com/pikaju/flutter-braintree/issues/74

**Comment by andesappal** [comment]
This worked https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side#generate-a-client-token
